name: colorful_iconify_flutter
description: 'complmentary icon library for iconify flutter'
version: 0.0.3
homepage: 'https://github.com/andronasef/iconify_flutter'

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: 'any'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
